### PR TITLE
Update pcs.py

### PR DESCRIPTION
**Pull request by zoubenjia**
Add error handling for HTTPError exception to cope with http 403 error.

### CODE REVIEW

**Comment by zoubenjia** [comment]
This is for issue #95

**Comment by PeterDing** [comment]
Can you make sure that the `403` status code is the unavailable signal of downloading url?

**Comment by zoubenjia** [comment]
> 
Hi Peter,


> Can you make sure that the `403` status code is the unavailable signal of downloading url?
I think 403 is "Forbidden". And the exception should now terminate the other downloading processes. 
BTW there was a type which I have just rectified.
Cheers
Ben

**Comment by PeterDing** [comment]
Thanks for your contribution.

**Pull request merged**
